quarkus:
  datasource:
    jdbc:
      url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
  log:
    console:
      async: true
    category:
      "com.pshs.ams":
        level: DEBUG