quarkus:
  datasource:
    jdbc:
      url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/ams_quarkus
    username: ${DB_USER}
    password: ${DB_PASS}
  log:
    console:
      async: true
    category:
      "com.pshs.ams":
        level: DEBUG
  http:
    host: 0.0.0.0
    port: 8080
    cors:
      origins: "*"

smallrye:
  jwt:
    sign:
      key:
        location: classpath:privateKey.pem
    verify:
      publickey:
        location: classpath:publicKey.pem

mp:
  jwt:
    verify:
      publickey:
        location: classpath:publicKey.pem
    sign:
      key:
        location: classpath:privateKey.pem